# -*- coding: utf-8 -*-
"""clase 25-3-25

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FxZMPcsLNW4jlmhhyzELgLKGfFKX_AJE
"""

router=[]
switch=[]
ap=[]
fw=[]
varios=[]
lista= ["R1","R2","R3","R4",
        "S1","S2","S3","AP1","AP2","AP3",
        "FW1","FW2","PC1","PC2","PC3", "TL1", "TL2"]
for item in lista:
  if "R" in item:
    router.append(item)
  elif "S" in item:
    switch.append(item)
  elif "AP" in item:
    ap.append(item)
  elif "FW" in item:
    fw.append(item)
  else:
    varios.append(item)
print(router)
print(switch)
print(ap)
print(fw)
print(varios)